INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Safemode

Safemode_FILES = Tweak.x
Safemode_CFLAGS = -Wno-c++11-compat-deprecated-writable-strings

include $(THEOS_MAKE_PATH)/tweak.mk
